server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Okta configuration for API Gateway
okta:
  oauth2:
    issuer: https://dev-93715225.okta.com/oauth2/default
    client-id: 0oaa0gl9zwOeSerQ85d7
    audience: api://default
    client-secret: uIQsvTsQyqx4zECLq1YfSYmvF8tB8tKEEG4rKhGw
    scopes: openid, profile, email, offline_access
